---
- hosts: all
  gather_facts: false

  vars_files:
    - ansible-external-vars.yml

  tasks:

    - name: Destroy terraform
      shell: "/home/{{ ansible_user }}/.local/bin/terraform destroy --var-file=credentials.tfvars --auto-approve"
      args:
        chdir: "{{ kubespray_install_dir }}/kubespray-{{ kubespray_version }}/contrib/terraform/aws"

    - name: Delete terraform state.
      file:
        path: /home/{{ ansible_user }}/.terraform.d
        state: absent

    - name: Delete Inventory
      file:
        path: "{{ kubespray_install_dir }}/kubespray-{{ kubespray_version }}/inventory/hosts"
        state: absent
