---
- hosts: all
  gather_facts: false

  vars_files:
    - ansible-external-vars.yml

  tasks:

    - name: upgrade all packages
      become: yes
      yum:
        name: '*'
        state: latest
      vars:
        ansible_python_interpreter: /usr/bin/python

    #
    # The python3-dnf package is not being found. So I am using yum 
    # instead of dnf.
    #
    - name: install packages with python2
      become: yes
      yum:
        name:
          - epel-release
        state: latest
        update_cache: yes
      vars:
        ansible_python_interpreter: /usr/bin/python

    - name: install packages with python2
      become: yes
      yum:
        name:
          - ansible
          - curl
          - jq
          - libselinux-python3
          - openssl
          - python2-jmespath
          - python3
          - python3-pip
          - unzip
        state: latest
        update_cache: yes
      vars:
        ansible_python_interpreter: /usr/bin/python

    - name: Upgrade pip
      pip:
          name: pip
          state: latest

    - name: Install pipenv package
      pip:
        name: pipenv
        state: latest
        executable: /usr/bin/pip3
        extra_args: --user

    - name: does venv exist?
      stat:
        path: "/home/{{ ansible_user }}/venv"
      register: venv_result

    - name: Create python virtual environment
      shell: python3 -m venv venv
      when: venv_result.stat.exists == false

    - name: Install python packages
      pip:
        name: [ "wheel", "ansible", "netaddr" ]
        state: latest

    - name: Setup python venv at login
      become: yes
      copy:
        dest: /etc/profile.d/venv.sh
        content: |
          source $HOME/venv/bin/activate
          cd {{ kubespray_install_dir }}/kubespray-{{ kubespray_version }}
