---
- hosts: all
  gather_facts: false

  vars_files:
    - external_vars.yml

  tasks:

    - name: Initialize terraform
      shell: "/home/{{ ansible_user }}/.local/bin/terraform init"
      args:
        creates: "/home/{{ ansible_user }}/.terraform.d/checkpoint_cache"
        chdir: "{{ kubespray_install_dir }}/kubespray-{{ kubespray_version }}/contrib/terraform/aws"

    - name: Apply terraform
      shell: "/home/{{ ansible_user }}/.local/bin/terraform apply --var-file=credentials.tfvars --auto-approve"
      args:
        creates: "{{ kubespray_install_dir }}/kubespray-{{ kubespray_version }}/inventory/hosts"
        chdir: "{{ kubespray_install_dir }}/kubespray-{{ kubespray_version }}/contrib/terraform/aws"
